spring.application.name=ecommerce

spring.security.enabled=false
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=planetaryy
spring.datasource.password=qpads95

api.security.token.secret=${JWT_SECRET:my-secret-key}

app.cors.allowed-origins=http://localhost:3000,http://127.0.0.1:3000


# PostgreSQL
# spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
# spring.datasource.username=ecommerce
# spring.datasource.password=ecommerce
# spring.jpa.hibernate.ddl-auto=update

# Kafka
#spring.kafka.bootstrap-servers=localhost:9092